package aitools

import (
	"fmt"
	"os"
	"path/filepath"
)

const generatedMarker = "<!-- generated by runweaver; safe to regenerate -->"

// MaterializeProfile writes generated metadata for all supported runtimes.
func MaterializeProfile(root string, profile Profile, force bool) error {
	return materializeOpenCodeProfile(root, profile, force)
}

// MaterializeProfileForRuntimes writes generated metadata for selected runtimes.
func MaterializeProfileForRuntimes(root string, profile Profile, force bool, runtimes []string) error {
	if len(runtimes) == 0 {
		runtimes = []string{RuntimeOpenCode}
	}
	for _, runtimeID := range runtimes {
		adapter, ok := RuntimeAdapterByID(runtimeID)
		if !ok {
			return fmt.Errorf("unsupported runtime %q", runtimeID)
		}
		if err := adapter.MaterializeProfile(root, profile, force); err != nil {
			return err
		}
	}
	return nil
}

func materializeOpenCodeProfile(root string, profile Profile, force bool) error {
	desiredAgents := map[string]bool{}
	desiredSkills := map[string]bool{}
	keepRuntimeBaselineFiles(root, desiredAgents, desiredSkills,
		[]string{
			".opencode/agents/swarm.md",
			".opencode/agents/repo-classifier.md",
			".opencode/agents/repo-surface-indexer.md",
			".opencode/agents/agent-skill-drift-reviewer.md",
			".opencode/agents/profile-regenerator.md",
			".opencode/agents/stale-anchor-fixer.md",
			".opencode/agents/repo-surface-engineer.md",
			".opencode/agents/repo-contract-reviewer.md",
			".opencode/agents/repo-test-quality-reviewer.md",
		},
		[]string{
			".opencode/skills/context-discipline/SKILL.md",
			".opencode/skills/metadata-refresh/SKILL.md",
			".opencode/skills/repo-onboarding/SKILL.md",
		},
	)
	for _, repo := range profile.Repos {
		for _, agent := range repo.Agents {
			if agent.Name != "" {
				desiredAgents[filepath.Join(root, ".opencode", "agents", agent.Name+".md")] = true
			}
		}
		for _, skill := range repo.CustomSkills {
			if skill.Name != "" {
				desiredSkills[filepath.Join(root, ".opencode", "skills", skill.Name, "SKILL.md")] = true
			}
		}
	}
	if force {
		if err := cleanupStaleGeneratedMetadata(root, desiredAgents, desiredSkills); err != nil {
			return err
		}
	}
	for _, repo := range profile.Repos {
		for _, agent := range repo.Agents {
			path := filepath.Join(root, ".opencode", "agents", agent.Name+".md")
			if err := writeGenerated(path, agentMarkdown(agent, repo), force); err != nil {
				return err
			}
		}
		for _, skill := range repo.CustomSkills {
			path := filepath.Join(root, ".opencode", "skills", skill.Name, "SKILL.md")
			if err := writeGenerated(path, skillMarkdown(skill, repo), force); err != nil {
				return err
			}
		}
	}
	return nil
}

func materializeCodexProfile(root string, profile Profile, force bool) error {
	desiredAgents := map[string]bool{}
	desiredSkills := map[string]bool{}
	keepRuntimeBaselineFiles(root, desiredAgents, desiredSkills,
		[]string{
			".codex/agents/swarm.toml",
		},
		[]string{
			".agents/skills/context-discipline/SKILL.md",
			".agents/skills/metadata-refresh/SKILL.md",
			".agents/skills/repo-onboarding/SKILL.md",
		},
	)
	for _, repo := range profile.Repos {
		for _, agent := range repo.Agents {
			if agent.Name != "" {
				desiredAgents[filepath.Join(root, ".codex", "agents", agent.Name+".toml")] = true
			}
		}
		for _, skill := range repo.CustomSkills {
			if skill.Name != "" {
				desiredSkills[filepath.Join(root, ".agents", "skills", skill.Name, "SKILL.md")] = true
			}
		}
	}
	if force {
		if err := cleanupGeneratedFilesWithSuffixes(filepath.Join(root, ".codex", "agents"), desiredAgents, []string{".toml"}); err != nil {
			return err
		}
		if err := cleanupGeneratedSkillFiles(filepath.Join(root, ".agents", "skills"), desiredSkills); err != nil {
			return err
		}
	}
	for _, repo := range profile.Repos {
		for _, agent := range repo.Agents {
			path := filepath.Join(root, ".codex", "agents", agent.Name+".toml")
			if err := writeGenerated(path, codexAgentTOML(agent, repo), force); err != nil {
				return err
			}
		}
		for _, skill := range repo.CustomSkills {
			path := filepath.Join(root, ".agents", "skills", skill.Name, "SKILL.md")
			if err := writeGenerated(path, codexSkillMarkdown(skill, repo), force); err != nil {
				return err
			}
		}
	}
	return nil
}

func materializeClaudeProfile(root string, profile Profile, force bool) error {
	desiredAgents := map[string]bool{}
	desiredSkills := map[string]bool{}
	keepRuntimeBaselineFiles(root, desiredAgents, desiredSkills,
		[]string{
			".claude/agents/swarm.md",
		},
		[]string{
			".claude/skills/context-discipline/SKILL.md",
			".claude/skills/metadata-refresh/SKILL.md",
			".claude/skills/repo-onboarding/SKILL.md",
		},
	)
	for _, repo := range profile.Repos {
		for _, agent := range repo.Agents {
			if agent.Name != "" {
				desiredAgents[filepath.Join(root, ".claude", "agents", agent.Name+".md")] = true
			}
		}
		for _, skill := range repo.CustomSkills {
			if skill.Name != "" {
				desiredSkills[filepath.Join(root, ".claude", "skills", skill.Name, "SKILL.md")] = true
			}
		}
	}
	if force {
		if err := cleanupGeneratedFiles(filepath.Join(root, ".claude", "agents"), desiredAgents); err != nil {
			return err
		}
		if err := cleanupGeneratedSkillFiles(filepath.Join(root, ".claude", "skills"), desiredSkills); err != nil {
			return err
		}
	}
	for _, repo := range profile.Repos {
		for _, agent := range repo.Agents {
			path := filepath.Join(root, ".claude", "agents", agent.Name+".md")
			if err := writeGenerated(path, claudeAgentMarkdown(agent, repo), force); err != nil {
				return err
			}
		}
		for _, skill := range repo.CustomSkills {
			path := filepath.Join(root, ".claude", "skills", skill.Name, "SKILL.md")
			if err := writeGenerated(path, claudeSkillMarkdown(skill, repo), force); err != nil {
				return err
			}
		}
	}
	return nil
}

func keepRuntimeBaselineFiles(root string, desiredAgents, desiredSkills map[string]bool, agents, skills []string) {
	for _, path := range agents {
		desiredAgents[filepath.Join(root, path)] = true
	}
	for _, path := range skills {
		desiredSkills[filepath.Join(root, path)] = true
	}
}

func writeGenerated(path, content string, force bool) error {
	if Exists(path) {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !hasGeneratedMarker(data) {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
